### ISSUE TITLE
Certificados com horas incorretas

### ISSUE THREAD

**Issue by samirfor** [comsolid/sige#20]
Corrigir o erro das horas mostradas incorretamente nos certificados quando o PostgreSQL está configurado com a hora incorreta.

**Comment by atilacamurca** [comment]
Descobri o problema, faltava uma restrição em uma tabela com chave primária dupla.

**Comment by atilacamurca** [comment]
Aproveitar e ordenar os certificados corretamente do mais atual para o menos atual.
