### ISSUE TITLE
Editar template do certificado com parâmetros nomeados

### ISSUE THREAD

**Issue by atilacamurca** [comsolid/sige#25]
Na tela `/admin/encontro/editar-mensagem-certificado/` a edição dos valores dinâmicos do certificado é feito através de `%s`. Isso torna difícil para o usuário saber quais os parâmetros que ele tem a sua disposição, além de não saber a ordem em que irão aparecer.

Assim sendo é necessário que os parâmetros sejam nomeados (ex. `%s(nome)` ou `%nome%`) e que na documentação da página mostre quais parâmetros ele tem a disposição.

**Comment by samirfor** [comment]
Na verdade, é preciso que os parâmetros seja nomeados dinamicamente,
conforme o usuário queira.

Em 15 de março de 2015 12:35, Átila Camurça Alves <notifications@github.com>
escreveu:

> Na tela /admin/encontro/editar-mensagem-certificado/ a edição dos valores
> dinâmicos do certificado é feito através de %s. Isso torna difícil para o
> usuário saber quais os parâmetros que ele tem a sua disposição, além de não
> saber a ordem em que irão aparecer.
>
> Assim sendo é necessário que os parâmetros sejam nomeados (ex. %s(nome)
> ou %nome%) e que na documentação da página mostre quais parâmetros ele
> tem a disposição.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/comsolid/sige/issues/25>.
>



-- 
Samir C. Costa
Blog samirfor.com <http://www.samirfor.com>
Software Developer
Student of computing in ifce <http://goog_1249115060>.edu.br
COMSOLiD.org member
