### ISSUE TITLE
Adicionar tela de Informações do Sistema

### ISSUE THREAD

**Issue by atilacamurca** [comsolid/sige#36]
Criar uma tela de informações do sistema, mostrando:

* a versão dos programas instalados (php, postgresql, apache ou nginx)
* hora do sistema e hora do banco de dados
* informações do php

Exemplo:

![system-info-mockup](https://cloud.githubusercontent.com/assets/508624/7078772/c3578a70-def2-11e4-84af-a863453ce831.png)

**Comment by atilacamurca** [comment]
related: <http://stackoverflow.com/a/2069415/1152679>

**Comment by samirfor** [comment]
Libzinha q eu achei: https://github.com/jrgp/linfo
