### ISSUE TITLE
Reativar funcionalidade de Tags

### ISSUE THREAD

**Issue by SrMouraSilva** [comsolid/sige#62]
Seria interessante que houvesse um sistema de tags funcional, onde usuários poderiam filtrar as palestras por determinado assunto.

**Observações**
- Na submissão de trabalhos, existe um campo "tecnologias envolvidas" que não encontrei uso em canto algum. Isso é aquele campo das versões anteriores para preencher quais são as necessidades do palestante?
- Na descrição de trabalhos, existe uma aba _Tags_ que não achei para preencher no campo de edição (nem por modo de usuário, nem por administrativo)

**Comment by samirfor** [comment]
Um pull request é sempre bem-vindo. :smile:

**Comment by atilacamurca** [comment]
**Tecnologias envolvidas** serve para o palestrante indicar que ferramentas ele vai utilizar para que os organizadores possam saber o que deve ser instalado ou o que deve ser deixado preparado nos laboratórios para sua palestra.
