### ISSUE TITLE
Implementar design responsivo para e-mail

### ISSUE THREAD

**Issue by samirfor** [comsolid/sige#63]
Usar https://mjml.io/

**Comment by atilacamurca** [comment]
Implementado e submetido para o repositório <https://github.com/comsolid/comsolid-email-templates>

A ideia é que seja separado o repositórios pois os arquivo `.mjml` devem ser "compilados" (transformados em HTML), por isso não quis submeter para cá.

Hoje, ao criar um Encontro, um template HTML responsivo para e-mail já é carregado por padrão, mas a saída é tão difícil de editar (pois se trata de um arquivo com várias tags cada uma com estilo _inline_), que não valia a pena. No final das contas eu editava o arquivo fora do sistema e copiava a saída compilada.

### Ideia

Uma ideia que poderia ser implementada futuramente seria criar um editor `mjml` que ao clicar em salvar iria compilar para HTML diretamente do browser (salvando também o arquivo mjml original para edições futuras).
