### ISSUE TITLE
Tela Recuperar Senha com erro na imagem docker

### ISSUE THREAD

**Issue by atilacamurca** [comsolid/sige#68]
Ao abrir a tela `/recuperar-senha` aparece a mensagem:

```
Exception information:

Message: Image CAPTCHA requires FT fonts support
```

Provavelmente alguma dependência de fonte.

**Comment by samirfor** [comment]
Isso. O gd precisa ser compilado com as bibliotecas do freetype. Vou corrigir.

**Comment by samirfor** [comment]
fix @ #72
