### ISSUE TITLE
Captcha indisponível na tela http://sige.comsolid.org/recuperar-senha

### ISSUE THREAD

**Issue by brianmend** [comsolid/sige#80]
Captcha indisponível na tela http://sige.comsolid.org/recuperar-senha, Tentei pelos navegadores Firefox, Chrome e IE

**Comment by samirfor** [comment]
Não é um problema do sistema. Era apenas nossa VPS com disco cheio.

**Comment by brianmend** [comment]
Obrigado Samir,

Abraço!

Enviado do Email do Windows

De: Samir C. Costa<mailto:notifications@github.com>
Enviado: ‎segunda-feira‎, ‎23‎ de ‎outubro‎ de ‎2017 ‎17‎:‎29
Para: comsolid/sige<mailto:sige@noreply.github.com>
Cc: Brian Mendes<mailto:brianmend@outlook.com>, Author<mailto:author@noreply.github.com>


Não é um problema do sistema. Era apenas nossa VPS com disco cheio.
